### ISSUE TITLE
Create missing logic on the rest of the windows @bkaryna

### ISSUE THREAD

**Issue by Szymonexis** [5G-Pickles/CV-Designer#47]

**Comment by bkaryna** [comment]
WIP 🚀

**Comment by bkaryna** [comment]
@Szymonexis 👨🏻‍🏫

Finished implementing write/load data for education&employment history, looking neat so far 🚀 

Will finish write/load for soft, hard stills and other info tomorrow.

Known issues and tasks [_will be taken care of_]: 
❌ work on from/to dates logic (allow leaving "to" empty) ---> as a side note, it might require minor changes to UI;
❌ handle adding items to lists (education, employment, skills);
✅ disable date pickers [disabled].

**Comment by bkaryna** [comment]
@Szymonexis senpai: Finished writing basic logic for all scenes, creating this pull request as per our conversation. 

As to from/to dates, I believe prior changes to UI are required @Vyvr. User should be able to select sth similar to "ongoing"/"present" option, which will disable "to" datepicker. 

Work on adding items to lists will start tomorrow/today evening after work.

**Comment by bkaryna** [comment]
@Szymonexis 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/61482996/144746816-4d343e16-8aa8-4e54-ada5-6db0e10bf160.png">


@Vyvr meanwhile: 
<img width="537" alt="image" src="https://user-images.githubusercontent.com/61482996/144746863-a748d597-b429-4874-abb3-451eb4d3476a.png">

**Comment by Vyvr** [comment]
> @Szymonexis senpai: Finished writing basic logic for all scenes, creating this pull request as per our conversation. 
> 
> As to from/to dates, I believe prior changes to UI are required @Vyvr. User should be able to select sth similar to "ongoing"/"present" option, which will disable "to" datepicker. 
> 
> Work on adding items to lists will start tomorrow/today evening after work. 

Okay i'll do it but first let's talk about how should it Look like
