### ISSUE TITLE
Figure out a way to create dynamic div movement in react (snap div to grid in react) @vyvr

### ISSUE THREAD

**Issue by Szymonexis** [5G-Pickles/CV-Designer#65]
Checkout https://stackoverflow.com/questions/20926551/recommended-way-of-making-react-component-div-draggable

**Comment by Vyvr** [comment]
https://www.youtube.com/watch?v=FFUUhYhxh5Q

**Comment by Vyvr** [comment]
react-spring, react-use-gesture

**Comment by Szymonexis** [comment]
https://github.com/5G-Pickles/CV-Designer/issues/65#issuecomment-987018870 zajebiste, będziemy używać

**Comment by Szymonexis** [comment]
done
